version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: store

    networks:
      - mysql-network
    ports:
      - "3306:3306"

networks:
  mysql-network:
    driver: bridge
