version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
